version: '3'

services:
  selenium-hub:
    image: seleniarm/hub:latest
    container_name: selenium-arm-hub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"

  chrome:
    image: seleniarm/node-chromium:latest
    container_name: chrome-arm
    shm_size: 2gb
    depends_on:
      - selenium-hub
    ports:
      - "7900:7900"
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_VNC_NO_PASSWORD: 1


  firefox:
    image: seleniarm/node-firefox:latest
    container_name: firefox-arm
    shm_size: 2gb
    depends_on:
      - selenium-hub
    ports:
      - "7901:7900"
    environment:
      SE_EVENT_BUS_HOST: selenium-hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_VNC_NO_PASSWORD: 1

  tests:
    container_name: capitole_tests
    build:
      context: .
    depends_on:
      - chrome
      - firefox
    volumes:
      - ./reports:/app/reports
      - ./images:/app/images

